@startuml

!include Interfaces/IKirelGenericEntityFrameworkRepository.puml

class KirelGenericEntityFrameworkRepository<KeyType, EntityType>

 KirelGenericEntityFrameworkRepository .down.|> IKirelGenericEntityFrameworkRepository

@enduml